- name: install catalogue component
  hosts: catalogue
  become: yes
  tasks:
  - name: disable old nodejs and enable nodejs
    ansible.builtin.service:
     name: nodejs:18
     state: stopped
     enabled: yes


