- name: install catalogue component
  hosts: catalogue
  become: yes
  tasks:
  - name: disable old nodejs and enable nodejs
    ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y
  - name: Install nodejs
    ansible.builtin.yum:
      name: nodejs 
      state: installed
  - name: create roboshop user
    ansible.builtin.user:
     name: roboshop

